Trying:
    lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul
Expecting nothing
ok
Trying:
    lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]])
Expecting:
    [[7, 10], [15, 22]]
**********************************************************************
File "./tests/101-lazy_matrix_mul.txt", line 13, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]])
Expected:
    [[7, 10], [15, 22]]
Got:
    array([[ 7, 10],
           [15, 22]])
Trying:
    lazy_matrix_mul([[1, 2]], [[3, 4], [5, 6]])
Expecting:
    [[13, 16]]
**********************************************************************
File "./tests/101-lazy_matrix_mul.txt", line 18, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([[1, 2]], [[3, 4], [5, 6]])
Expected:
    [[13, 16]]
Got:
    array([[13, 16]])
Trying:
    list1 = [[1, 4, 7], [2, 5, 8], [3, 6, 9]]
Expecting nothing
ok
Trying:
    list2 = [[1, -1, 2], [2, -1, 2], [3, -3, 0]]
Expecting nothing
ok
Trying:
    lazy_matrix_mul(list1, list2)
Expecting:
    [[30, -26, 10], [36, -31, 14], [42, -36, 18]]
**********************************************************************
File "./tests/101-lazy_matrix_mul.txt", line 25, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul(list1, list2)
Expected:
    [[30, -26, 10], [36, -31, 14], [42, -36, 18]]
Got:
    array([[ 30, -26,  10],
           [ 36, -31,  14],
           [ 42, -36,  18]])
Trying:
    lazy_matrix_mul([[1, 5, 7]], [[3], [5], [8]])
Expecting:
    [[84]]
**********************************************************************
File "./tests/101-lazy_matrix_mul.txt", line 30, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([[1, 5, 7]], [[3], [5], [8]])
Expected:
    [[84]]
Got:
    array([[84]])
Trying:
    lazy_matrix_mul([], [[2, 5, 6]])
Expecting:
    Traceback (most recent call last):
          ...
    ValueError: m_a can't be empty
**********************************************************************
File "./tests/101-lazy_matrix_mul.txt", line 35, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([], [[2, 5, 6]])
Expected:
    Traceback (most recent call last):
          ...
    ValueError: m_a can't be empty
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest 101-lazy_matrix_mul.txt[7]>", line 1, in <module>
        lazy_matrix_mul([], [[2, 5, 6]])
      File "/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 8, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
    ValueError: shapes (0,) and (1,3) not aligned: 0 (dim 0) != 1 (dim 0)
Trying:
    lazy_matrix_mul([[7, 12]], [[]])
Expecting:
    Traceback (most recent call last):
              ...
    ValueError: m_b can't be empty
**********************************************************************
File "./tests/101-lazy_matrix_mul.txt", line 42, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([[7, 12]], [[]])
Expected:
    Traceback (most recent call last):
              ...
    ValueError: m_b can't be empty
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest 101-lazy_matrix_mul.txt[8]>", line 1, in <module>
        lazy_matrix_mul([[7, 12]], [[]])
      File "/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 8, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
    ValueError: shapes (1,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)
Trying:
    lazy_matrix_mul((1, 3, 5), [[1.3], [5.2], [7.7]])
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: m_a must be a list
**********************************************************************
File "./tests/101-lazy_matrix_mul.txt", line 49, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul((1, 3, 5), [[1.3], [5.2], [7.7]])
Expected:
    Traceback (most recent call last):
              ...
    TypeError: m_a must be a list
Got:
    array([55.4])
Trying:
    lazy_matrix_mul([[1, 2], [3, 4]], [1, 2])
Expecting:
    Traceback (most recent call last):
    TypeError: m_b must be a list of lists
**********************************************************************
File "./tests/101-lazy_matrix_mul.txt", line 54, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([[1, 2], [3, 4]], [1, 2])
Expected:
    Traceback (most recent call last):
    TypeError: m_b must be a list of lists
Got:
    array([ 5, 11])
Trying:
    lazy_matrix_mul([[3, 3], [4, 4]], "Holberton")
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: m_b must be a list
**********************************************************************
File "./tests/101-lazy_matrix_mul.txt", line 60, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([[3, 3], [4, 4]], "Holberton")
Expected:
    Traceback (most recent call last):
              ...
    TypeError: m_b must be a list
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest 101-lazy_matrix_mul.txt[11]>", line 1, in <module>
        lazy_matrix_mul([[3, 3], [4, 4]], "Holberton")
      File "/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 8, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
    ValueError: Scalar operands are not allowed, use '*' instead
Trying:
    lazy_matrix_mul([[]], ["Holberton"])
Expecting:
    Traceback (most recent call last):
          ...
    ValueError: m_a can't be empty
**********************************************************************
File "./tests/101-lazy_matrix_mul.txt", line 67, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([[]], ["Holberton"])
Expected:
    Traceback (most recent call last):
          ...
    ValueError: m_a can't be empty
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest 101-lazy_matrix_mul.txt[12]>", line 1, in <module>
        lazy_matrix_mul([[]], ["Holberton"])
      File "/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 8, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
    ValueError: shapes (1,0) and (1,) not aligned: 0 (dim 1) != 1 (dim 0)
Trying:
    lazy_matrix_mul([], [[1]])
Expecting:
    Traceback (most recent call last):
              ...
    ValueError: m_a can't be empty
**********************************************************************
File "./tests/101-lazy_matrix_mul.txt", line 74, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([], [[1]])
Expected:
    Traceback (most recent call last):
              ...
    ValueError: m_a can't be empty
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest 101-lazy_matrix_mul.txt[13]>", line 1, in <module>
        lazy_matrix_mul([], [[1]])
      File "/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 8, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
    ValueError: shapes (0,) and (1,1) not aligned: 0 (dim 0) != 1 (dim 0)
Trying:
    lazy_matrix_mul([[1, 2]], [[]])
Expecting:
    Traceback (most recent call last):
              ...
    ValueError: m_b can't be empty
**********************************************************************
File "./tests/101-lazy_matrix_mul.txt", line 81, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([[1, 2]], [[]])
Expected:
    Traceback (most recent call last):
              ...
    ValueError: m_b can't be empty
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest 101-lazy_matrix_mul.txt[14]>", line 1, in <module>
        lazy_matrix_mul([[1, 2]], [[]])
      File "/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 8, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
    ValueError: shapes (1,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)
Trying:
    lazy_matrix_mul([[1, '1', 1], ['2', 2, '2']], [[3], [3]])
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: m_a should contain only integers or floats
**********************************************************************
File "./tests/101-lazy_matrix_mul.txt", line 88, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([[1, '1', 1], ['2', 2, '2']], [[3], [3]])
Expected:
    Traceback (most recent call last):
              ...
    TypeError: m_a should contain only integers or floats
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest 101-lazy_matrix_mul.txt[15]>", line 1, in <module>
        lazy_matrix_mul([[1, '1', 1], ['2', 2, '2']], [[3], [3]])
      File "/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 8, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
    ValueError: shapes (2,3) and (2,1) not aligned: 3 (dim 1) != 2 (dim 0)
Trying:
    lazy_matrix_mul([[2, 4, 6], [3, 6, 9]], [[1], ['2'], [3]])
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: m_b should contain only integers or floats
**********************************************************************
File "./tests/101-lazy_matrix_mul.txt", line 95, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([[2, 4, 6], [3, 6, 9]], [[1], ['2'], [3]])
Expected:
    Traceback (most recent call last):
              ...
    TypeError: m_b should contain only integers or floats
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest 101-lazy_matrix_mul.txt[16]>", line 1, in <module>
        lazy_matrix_mul([[2, 4, 6], [3, 6, 9]], [[1], ['2'], [3]])
      File "/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 8, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
    TypeError: invalid data type for einsum
Trying:
    lazy_matrix_mul([[12, 12, 12], [], [14, 14, 14]], [[2], [3], [8]])
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: each row of m_a must be of the same size
**********************************************************************
File "./tests/101-lazy_matrix_mul.txt", line 102, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([[12, 12, 12], [], [14, 14, 14]], [[2], [3], [8]])
Expected:
    Traceback (most recent call last):
              ...
    TypeError: each row of m_a must be of the same size
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest 101-lazy_matrix_mul.txt[17]>", line 1, in <module>
        lazy_matrix_mul([[12, 12, 12], [], [14, 14, 14]], [[2], [3], [8]])
      File "/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 8, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
    ValueError: setting an array element with a sequence.
Trying:
    lazy_matrix_mul([[2, 2, 2], [4, 4, 4]], [[2], [3, 3]])
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: each row of m_b must be of the same size
**********************************************************************
File "./tests/101-lazy_matrix_mul.txt", line 109, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([[2, 2, 2], [4, 4, 4]], [[2], [3, 3]])
Expected:
    Traceback (most recent call last):
              ...
    TypeError: each row of m_b must be of the same size
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest 101-lazy_matrix_mul.txt[18]>", line 1, in <module>
        lazy_matrix_mul([[2, 2, 2], [4, 4, 4]], [[2], [3, 3]])
      File "/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 8, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
    ValueError: setting an array element with a sequence.
Trying:
    lazy_matrix_mul([[5, 2, 3], [7, 13, 2], [1, 0, 3]], [[2, 3], [6, 9]])
Expecting:
    Traceback (most recent call last):
              ...
    ValueError: m_a and m_b can't be multiplied
**********************************************************************
File "./tests/101-lazy_matrix_mul.txt", line 116, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([[5, 2, 3], [7, 13, 2], [1, 0, 3]], [[2, 3], [6, 9]])
Expected:
    Traceback (most recent call last):
              ...
    ValueError: m_a and m_b can't be multiplied
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest 101-lazy_matrix_mul.txt[19]>", line 1, in <module>
        lazy_matrix_mul([[5, 2, 3], [7, 13, 2], [1, 0, 3]], [[2, 3], [6, 9]])
      File "/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 8, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
    ValueError: shapes (3,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)
Trying:
    lazy_matrix_mul([[1, 2]])
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'
ok
Trying:
    lazy_matrix_mul()
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'
ok
**********************************************************************
1 items had failures:
  17 of  22 in 101-lazy_matrix_mul.txt
22 tests in 1 items.
5 passed and 17 failed.
***Test Failed*** 17 failures.
